<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Inquiry Reports</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .header h1 {
            color: #333;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .stats {
            display: table;
            width: 100%;
            margin-bottom: 30px;
        }
        .stat-item {
            display: table-cell;
            text-align: center;
            padding: 10px;
            border: 1px solid #ddd;
            background-color: #f9f9f9;
        }
        .stat-number {
            font-size: 18px;
            font-weight: bold;
            color: #2c3e50;
        }
        .stat-label {
            font-size: 11px;
            color: #666;
            margin-top: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
            font-size: 11px;
        }
        td {
            font-size: 10px;
        }
        .status-pending { color: #f39c12; }
        .status-in-progress { color: #3498db; }
        .status-resolved { color: #27ae60; }
        .status-closed { color: #95a5a6; }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Inquiry Management Reports</h1>
        <p>Report Period: {{ \Carbon\Carbon::parse($dateFrom)->format('M d, Y') }} - {{ \Carbon\Carbon::parse($dateTo)->format('M d, Y') }}</p>
        <p>Generated on: {{ now()->format('M d, Y \a\t H:i A') }}</p>
    </div>

    <div class="stats">
        <div class="stat-item">
            <div class="stat-number">{{ $stats['total'] }}</div>
            <div class="stat-label">Total Inquiries</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ $stats['pending'] }}</div>
            <div class="stat-label">Pending</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ $stats['in_progress'] }}</div>
            <div class="stat-label">In Progress</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ $stats['resolved'] }}</div>
            <div class="stat-label">Resolved</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ $stats['closed'] }}</div>
            <div class="stat-label">Closed</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 25%;">Title</th>
                <th style="width: 15%;">Status</th>
                <th style="width: 20%;">Submitter</th>
                <th style="width: 15%;">Date</th>
                <th style="width: 20%;">Category</th>
            </tr>
        </thead>
        <tbody>
            @foreach($inquiries as $index => $inquiry)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $inquiry->title }}</td>
                <td class="status-{{ strtolower(str_replace(' ', '-', $inquiry->status)) }}">
                    {{ $inquiry->status }}
                </td>
                <td>{{ $inquiry->user->name ?? 'N/A' }}</td>
                <td>{{ $inquiry->date_submitted ? \Carbon\Carbon::parse($inquiry->date_submitted)->format('M d, Y') : 'N/A' }}</td>
                <td>{{ $inquiry->category ?? 'N/A' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report contains {{ $inquiries->count() }} inquiries from the MCMC Inquiry Management System.</p>
        <p>Report generated by {{ Auth::user()->name ?? 'Admin' }} on {{ now()->format('F j, Y \a\t H:i A') }}</p>
    </div>
</body>
</html>
